### PR TITLE
Upload PkgEval logs to AWS.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@christopher-dG Keeping it PkgEval-specific for now, since that's by far the largest part of this repo, but feel free to adapt for BenchmarkJob. IIUC the current bucket is configured to expire its contents after 30 days, but I think we can configure that on an per-object basis too.

**Comment by christopher-dG** [comment]
Awesome! I don't think I'll have time to do this for quite some time, but I'll try to look into it eventually.

**Comment by maleadt** [comment]
Sure. Now that we'll upload to AWS, I'm thinking of scrubbing the NanosoldierReports repo from any logs. That would change hashes though, and invalidate the commit-specific links that are embedded in the reports. Thoughts? Maybe we shouldn't include the commit in the reports URLs to avoid this situation if we ever rewrite the history in the future again.

**Comment by christopher-dG** [comment]
Yeah I don't really mind rewriting the history, since I don't think those links are used much once they're more than a day or two old.

**Pull request merged**
