### PR TITLE
When creating or updating GitHub commit statuses, if the state is "failure", change it to "success"; otherwise, do not modify it

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@maleadt @staticfloat @christopher-dG Any idea why the nightly CI jobs are all failing?

**Comment by DilumAluthge** [comment]
Bump @maleadt. Does this look like the right way to go?

**Comment by DilumAluthge** [comment]
Bump @maleadt

**Comment by maleadt** [comment]
Sorry, I thought this was an issue and not a PR, hence me ignoring it until I got to do some CI development.

I don't think we should ignore `error` status codes though, which indicate misuse of the bot.

**Comment by DilumAluthge** [comment]
Ah, so only fails then?

**Comment by DilumAluthge** [comment]
Alright, we now only modify "failure" states.

**Comment by DilumAluthge** [comment]
Does the new commit get deployed automatically, or do I need to make a PR somewhere to e.g. update a manifest file?

**Comment by maleadt** [comment]
For PkgEval, I have to do it manually on `amdci8`. But I've done so already, so it should have been deployed already.

Somebody else (@christopher-dG?) will have to do it for the benchmarks bot.

**Comment by maleadt** [comment]
Or didn't @vtjnash set up a benchmark bot when the nanosoldier cluster died?

**Comment by vtjnash** [comment]
I currently manually update it, especially since it has suboptimal fall-over

**Pull request merged**
