### PR TITLE
Return 204 rather than 400 for issues

### PR DESCRIPTION
**Pull request by ararslan**
Otherwise the GitHub webhook log is all full of bad

### CODE REVIEW

**Comment by jrevels** [comment]
Hmm.  In our offline discussion, I was referring to [changing this response](https://github.com/JuliaWeb/GitHub.jl/blob/3cf3501f4f18de76ef5092e4f3e2345431107a3b/src/activity/events.jl#L105) to a `204` with a message ("event ignored" or something) and then adding issue comments to the server's blacklist/not sending them from the webhook in the first place. In that case, this response would just be deleted.

If we do continue to allow issue comments to get through (i.e. if this code actually stayed reachable), then it is indeed correct to throw a `400` if somebody actually was trying to submit a nanosoldier job. This is currently wrong only in that it doesn't check for an actual job submission.

**Comment by ararslan** [comment]
Okay, I've submitted a PR to GitHub.jl. Once that's merged and tagged I'll repurpose this PR to blacklist those kinds of events.

**Comment by ararslan** [comment]
Oh man. I don't even remember whether this is still a problem.

**Comment by vtjnash** [comment]
Seems like we don't even look at these logs? (are they full of bad?) and this is conflicted

**Pull request closed without merging**
